export const API_URL = "/ufc/v1/";
export const PLAYERS = [
  {
    textclass: "text-img009",
    id: 1,
    first_name: "Feather",
    last_name: "Weight",
    imageclass: "img009",
    imagepath: "img/009.png",
  },
  {
    textclass: "text-img007",
    id: 2,
    first_name: "Brantum",
    last_name: "Weight",
    imageclass: "img007",
    imagepath: "img/007.png",
  },
  {
    textclass: "text-img003",
    id: 3,
    first_name: "Middle",
    last_name: "Weight",
    imageclass: "img003",
    imagepath: "img/003.png",
  },
  {
    textclass: "text-img002",
    id: 4,
    first_name: "Light Heavy",
    last_name: "Weight",
    imageclass: "img002",
    imagepath: "img/002.png",
  },
  {
    textclass: "text-img001",
    id: 5,
    first_name: "Straw",
    last_name: "Weight",
    imageclass: "img001",
    imagepath: "img/001.png",
  },
  {
    textclass: "text-img004",
    id: 6,
    first_name: "Heavy",
    last_name: "Weight",
    imageclass: "img004",
    imagepath: "img/004.png",
  },
  {
    textclass: "text-img005",
    id: 7,
    first_name: "Fly",
    last_name: "Weight",
    imageclass: "img005",
    imagepath: "img/005.png",
  },
  {
    textclass: "text-img008",
    id: 8,
    first_name: "Light",
    last_name: "Weight",
    imageclass: "img008",
    imagepath: "img/008.png",
  },
  {
    textclass: "text-img006",
    id: 9,
    first_name: "Welter",
    last_name: "Weight",
    imageclass: "img006",
    imagepath: "img/006.png",
  },
];
